"use client";

import React from "react";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";

type CountKind = "mcq" | "coding";
const limits = { mcq: 100, coding: 10 } as const;

export function AssessmentBuilder() {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [mcq, setMcq] = useState(30); const [coding, setCoding] = useState(3); const [duration, setDuration] = useState(60);
  const [topics, setTopics] = useState(""); const [difficulty, setDifficulty] = useState(""); const [locale, setLocale] = useState("en"); const [languages, setLanguages] = useState("JAVA");
  const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [success, setSuccess] = useState<{ assessmentId: string; versionNumber: number; questionCount: number; questionTypeCounts: Record<string, number> } | null>(null);
  const total = mcq + coding;
  const filters = useMemo(() => ({ taxonomyAll: topics.split(",").map(value => value.trim()).filter(Boolean).map(code => ({ scheme: "topic", code })), difficultyProfiles: difficulty.trim() ? [{ scheme: "mockarena-v1", code: difficulty.trim().toUpperCase() }] : [], contentLocales: locale.split(",").map(value => value.trim().toLowerCase()).filter(Boolean) }), [topics, difficulty, locale]);
  const valid = title.trim().length > 0 && mcq >= 0 && mcq <= 100 && coding >= 0 && coding <= 10 && total >= 10 && total <= 110 && duration > 0;
  function change(kind: CountKind, next: number) { (kind === "mcq" ? setMcq : setCoding)(Math.max(0, Math.min(limits[kind], next))); }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (!valid) { setError("Use 0–100 MCQ, 0–10 Coding, and 10–110 total questions."); return; } const selectionGroups = [mcq > 0 && { ...filters, questionTypeCodes: ["MCQ"], requestedQuestionCount: mcq, programmingLanguages: [] }, coding > 0 && { ...filters, questionTypeCodes: ["CODING"], requestedQuestionCount: coding, programmingLanguages: languages.split(",").map(value => value.trim().toUpperCase()).filter(Boolean) }].filter(Boolean); setPending(true); try { const response = await fetch("/api/creator/assessments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, description, durationMinutes: duration, selectionGroups }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.code === "QUESTION_SELECTION_INSUFFICIENT" ? "MockArena currently does not have enough matching questions for this configuration. Reduce the question count or broaden your filters." : body.code === "UNAUTHENTICATED" ? "Your session has expired. Please log in again." : "Assessment creation could not be completed. A published Challenge may need creator follow-up before retrying."); return; } setSuccess(body); } catch { setError("Network error. Please try again."); } finally { setPending(false); } }
  if (success) return <section className="panel"><h1>Assessment created successfully</h1><p>{title} · {success.questionCount} questions · {duration} minutes</p><p>{success.questionTypeCounts.MCQ ?? 0} MCQ · {success.questionTypeCounts.CODING ?? 0} Coding</p><div className="card-actions"><Link className="button" href={`/assessments/${success.assessmentId}`}>View Assessment</Link><Link className="button secondary" href={`/assessments/${success.assessmentId}/take`}>Take Assessment</Link><button className="button secondary" onClick={() => setSuccess(null)}>Create Another</button></div></section>;
  return <form className="builder" onSubmit={submit}><h1>Create custom assessment</h1><p className="muted">Challenge composition is resolved and validated by MockArena. Topics and difficulty are free-form generic metadata until a taxonomy catalogue is available.</p><label>Assessment title<input value={title} onChange={event => setTitle(event.target.value)} required maxLength={200} /></label><label>Description<textarea className="short-textarea" value={description} onChange={event => setDescription(event.target.value)} maxLength={10000} /></label><fieldset><legend>Question composition</legend>{(["mcq", "coding"] as CountKind[]).map(kind => <div className="counter" key={kind}><span>{kind === "mcq" ? "MCQ" : "Coding"}</span><button type="button" aria-label={`Decrease ${kind}`} onClick={() => change(kind, (kind === "mcq" ? mcq : coding) - 1)}>−</button><output>{kind === "mcq" ? mcq : coding}</output><button type="button" aria-label={`Increase ${kind}`} onClick={() => change(kind, (kind === "mcq" ? mcq : coding) + 1)}>+</button></div>)}</fieldset><p><strong>Total questions: {total}</strong> <span className="muted">(MCQ 0–100; Coding 0–10; total 10–110)</span></p><label>Topics / taxonomy (comma-separated codes)<input value={topics} onChange={event => setTopics(event.target.value)} placeholder="software-engineering" /><span className="muted">Topic values depend on the available question bank.</span></label><label>Difficulty profile code<input value={difficulty} onChange={event => setDifficulty(event.target.value)} placeholder="MEDIUM" /></label><label>Content locale (comma-separated)<input value={locale} onChange={event => setLocale(event.target.value)} /></label>{coding > 0 && <label>Programming languages for Coding (comma-separated)<input value={languages} onChange={event => setLanguages(event.target.value)} /></label>}<label>Duration<select value={duration} onChange={event => setDuration(Number(event.target.value))}>{[30,45,60,90,120].map(minutes => <option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label><aside className="panel"><h2>Custom Assessment</h2><p>{mcq} MCQ · {coding} Coding · {total} questions · {duration} minutes</p><p className="muted">PUBLIC · STANDARD · one attempt · immediate results</p></aside>{error && <p className="error" role="alert">{error}</p>}<button className="button" disabled={pending || !valid}>{pending ? "Creating…" : "Create Assessment"}</button></form>;
}
