package com.mockarena.runner;

import com.mockarena.runner.api.*; import com.mockarena.runner.infrastructure.DockerJavaSandbox;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.condition.EnabledIfSystemProperty; import java.util.*;
import static org.assertj.core.api.Assertions.*;

/** Explicit only: runs hostile-code-adjacent Docker checks, never part of ordinary Maven tests. */
@EnabledIfSystemProperty(named="mockarena.runner.docker-tests",matches="true") class DockerJavaSandboxIntegrationTest {
 private final DockerJavaSandbox sandbox=new DockerJavaSandbox("docker","mockarena-java-runner:21-v1",true,512,65536,32,1);
 @Test void runsJavaAsIsolatedNonRootContainerAndComparesWhitespace(){var source="import java.io.*; class Main { public static void main(String[] a)throws Exception { System.out.println(\"  hello   world \" ); } }";var response=sandbox.execute(request(source,"hello world"));assertThat(response.status()).isEqualTo("COMPLETED");assertThat(response.testsPassed()).isEqualTo(1);}
 @Test void compilerErrorAndInfiniteLoopAreCandidateOutcomes(){assertThat(sandbox.execute(request("class Main {","")).candidateFailureCategory()).isEqualTo("COMPILE_ERROR");assertThat(sandbox.execute(request("class Main { public static void main(String[] a){while(true){} } }","")).candidateFailureCategory()).isEqualTo("TIME_LIMIT_EXCEEDED");}
 @Test void supportsStdinWrongAnswersAndRuntimeErrors(){String sum="import java.util.*; public class Main { public static void main(String[] a) { Scanner s=new Scanner(System.in); System.out.println(s.nextInt()+s.nextInt()); } }";assertThat(sandbox.execute(request(sum,"2 3","5")).testsPassed()).isEqualTo(1);assertThat(sandbox.execute(request(sum,"2 3","6")).testsPassed()).isZero();assertThat(sandbox.execute(request("public class Main { public static void main(String[] a) { throw new RuntimeException(); } }","","")).candidateFailureCategory()).isEqualTo("RUNTIME_ERROR");}
 @Test void outputCeilingNonRootAndNoNetworkAreEnforced(){String flood="public class Main { public static void main(String[] a) { while(true) System.out.print(\"x\"); } }";assertThat(sandbox.execute(request(flood,"", "",128)).candidateFailureCategory()).isEqualTo("OUTPUT_LIMIT_EXCEEDED");String identity="public class Main { public static void main(String[] a) { System.out.println(System.getProperty(\"user.name\")); } }";assertThat(sandbox.execute(request(identity,"","mockarena")).testsPassed()).isEqualTo(1);String network="import java.net.*; public class Main { public static void main(String[] a) { try { new Socket(\"1.1.1.1\",80); System.out.println(\"NETWORK\"); } catch(Exception e) { System.out.println(\"DENIED\"); } } }";assertThat(sandbox.execute(request(network,"","DENIED")).testsPassed()).isEqualTo(1);}
 @Test void removesLabeledContainerAfterSuccessAndFailure() throws Exception {ExecutionRequest success=request("public class Main { public static void main(String[] a){} }","","");sandbox.execute(success);assertThat(containers(success.jobId())).isBlank();ExecutionRequest failure=request("class Main {","","");sandbox.execute(failure);assertThat(containers(failure.jobId())).isBlank();}
 private static ExecutionRequest request(String source,String expected){return request(source,"",expected);} private static ExecutionRequest request(String source,String input,String expected){return request(source,input,expected,65536);} private static ExecutionRequest request(String source,String input,String expected,int maxOutput){return new ExecutionRequest(UUID.randomUUID(),"JAVA","java-21-stdio-v1",source,new ExecutionRequest.Limits(5000,500,256,maxOutput,64),List.of(new ExecutionRequest.TestCase(input,expected,"NORMALIZED_WHITESPACE")));}
 private static String containers(UUID jobId) throws Exception {Process p=new ProcessBuilder("docker","ps","-aq","--filter","label=mockarena.runner.job="+jobId).start();p.waitFor();return new String(p.getInputStream().readAllBytes()).trim();}
}
