"use client";
import Link from "next/link";
import React,{useCallback,useEffect,useRef,useState}from"react";
import{useQuery}from"@tanstack/react-query";
import{BffError,browserApi}from"@/lib/api/browser-client";
import type{AttemptResult,CandidateQuestion,SaveResponseInput,SavedResponse}from"@/lib/api/contracts";
import{CodingEditor}from"./coding-editor";
type Flush=()=>Promise<void>;const langs=(v:unknown)=>Array.isArray(v)?v.filter((x):x is string=>typeof x==="string"):[];

export function AttemptWorkspace({attemptId}:{attemptId:string}){
 const[local,setLocal]=useState<Record<number,SavedResponse>>({}),[inactive,setInactive]=useState(false),[submitting,setSubmitting]=useState(false),[submitted,setSubmitted]=useState(false),[confirm,setConfirm]=useState(false),[error,setError]=useState("");
 const content=useQuery({queryKey:["attempt-content",attemptId],queryFn:()=>browserApi.content(attemptId)}),saved=useQuery({queryKey:["attempt-responses",attemptId],queryFn:()=>browserApi.responses(attemptId),enabled:!content.isError}),result=useQuery({queryKey:["attempt-result",attemptId],queryFn:()=>browserApi.result(attemptId),enabled:submitted||content.isError,retry:false});
 const versions=useRef<Record<number,number>>({}),queue=useRef<Record<number,Promise<void>>>({}),flushers=useRef<Record<number,Flush>>({}),key=useRef<string|null>(null);
 useEffect(()=>{if(saved.data){const values:Record<number,SavedResponse>={};saved.data.forEach(r=>{values[r.globalPosition]=r;versions.current[r.globalPosition]=r.version;});setLocal(values);}},[saved.data]);
 const save=useCallback((position:number,make:(version:number)=>Omit<SaveResponseInput,"expectedResponseVersion"|"clientMutationId">)=>{if(inactive||submitting)return Promise.resolve();const work=async()=>{const response=await browserApi.saveResponse(attemptId,position,{...make(versions.current[position]??0),expectedResponseVersion:versions.current[position]??0,clientMutationId:crypto.randomUUID()},crypto.randomUUID());versions.current[position]=response.version;setLocal(current=>({...current,[position]:response}));};return queue.current[position]=(queue.current[position]??Promise.resolve()).catch(()=>undefined).then(work);},[attemptId,inactive,submitting]);
 const submit=async()=>{setSubmitting(true);setError("");try{await Promise.all(Object.values(flushers.current).map(flush=>flush()));await Promise.all(Object.values(queue.current));const submissionKey=key.current??crypto.randomUUID();key.current=submissionKey;await browserApi.submit(attemptId,submissionKey);setInactive(true);setSubmitted(true);setConfirm(false);void result.refetch();}catch{setSubmitting(false);setError("Your latest response could not be saved or submitted. Please review and try again.");}};
 if(submitted||content.isError)return <SubmittedAttemptResult result={result} onRefresh={()=>void result.refetch()}/>;
 const question=content.data?.items[0];if(!question||content.isLoading||saved.isLoading)return <main className="attempt-main">Loading assessment content…</main>;
 return <main className="attempt-main"><Question question={question} response={local[question.position]} disabled={inactive||submitting} onSave={save} register={flush=>{flushers.current[question.position]=flush;}}/>{confirm?<section className="panel"><h2>Submit assessment?</h2><p>You will no longer be able to change your answers after submission.</p><button onClick={()=>setConfirm(false)}>Cancel</button><button onClick={()=>void submit()} disabled={submitting}>Submit</button></section>:<button disabled={inactive||submitting} onClick={()=>setConfirm(true)}>Submit Assessment</button>}{error&&<p className="error" role="alert">{error}</p>}</main>;
}

function SubmittedAttemptResult({result,onRefresh}:{result:ReturnType<typeof useQuery<AttemptResult>>;onRefresh:()=>void}){
 if(result.isLoading)return <main className="attempt-main">Loading result…</main>;
 if(result.error instanceof BffError&&result.error.code==="RESULT_NOT_RELEASED")return <Shell title="Assessment submitted successfully"><p>Results are not available yet.</p><Actions/></Shell>;
 if(result.isError||!result.data)return <Shell title="Assessment submitted successfully"><p className="error" role="alert">We could not load your result right now.</p><button className="button secondary" onClick={onRefresh}>Refresh result</button><Actions/></Shell>;
 const data=result.data;if(data.evaluationStatus==="PENDING")return <Shell title="Assessment submitted successfully"><p>Evaluation in progress.</p><p>Your responses have been saved.</p><button className="button secondary" onClick={onRefresh}>Refresh result</button><Actions/></Shell>;
 if(data.evaluationStatus==="PARTIALLY_EVALUATED")return <Shell title="Evaluation partially complete"><p>MCQ evaluation complete</p><p>Coding evaluation pending</p><ResultItemList items={data.items}/><Actions/></Shell>;
 return <Shell title="Assessment result"><ResultSummary result={data}/><ResultItemList items={data.items}/><Actions/></Shell>;
}
function Shell({title,children}:{title:string;children:React.ReactNode}){return <main className="attempt-main"><h1>{title}</h1>{children}</main>;}
function ResultSummary({result}:{result:AttemptResult}){return <section className="panel"><h2>Score</h2><p>{result.score} / {result.maxScore}</p><p>{result.percentage}%</p></section>;}
function ResultItemList({items}:{items:AttemptResult["items"]}){return <section className="panel"><h2>Question outcomes</h2><ul>{items.map(item=><li key={item.globalPosition}>Question {item.globalPosition} — {item.evaluationStatus==="PENDING"?"Pending evaluation":item.outcome==="CORRECT"?"Correct":item.outcome==="INCORRECT"?"Incorrect":"Unanswered"}</li>)}</ul></section>;}
function Actions(){return <p><Link className="button secondary" href="/candidate">Back to Dashboard</Link> <Link className="button secondary" href="/assessments">Browse Assessments</Link></p>;}

function Question({question,response,disabled,onSave,register}:{question:CandidateQuestion;response?:SavedResponse;disabled:boolean;onSave:(position:number,make:(version:number)=>Omit<SaveResponseInput,"expectedResponseVersion"|"clientMutationId">)=>Promise<void>;register:(flush:Flush)=>void}){const[code,setCode]=useState(response?.sourceCode??""),[language,setLanguage]=useState(response?.programmingLanguage??langs(question.programmingLanguages)[0]??"");const timer=useRef<ReturnType<typeof setTimeout>|null>(null),pending=useRef<{language:string;source:string}|null>(null);const flush=useCallback(async()=>{if(timer.current)clearTimeout(timer.current);timer.current=null;const next=pending.current;pending.current=null;if(next)await onSave(question.position,()=>({responseTypeCode:"CODING",programmingLanguage:next.language,sourceCode:next.source}));},[onSave,question.position]);useEffect(()=>{register(flush);return()=>{if(timer.current)clearTimeout(timer.current);};},[flush,register]);useEffect(()=>{if(response?.sourceCode!==undefined)setCode(response.sourceCode??"");if(response?.programmingLanguage)setLanguage(response.programmingLanguage);},[response]);if(question.questionTypeCode==="MCQ")return <div>{question.options.map(option=><label key={option.id}><input type="radio" disabled={disabled} checked={response?.selectedOptionId===option.id} onChange={()=>void onSave(question.position,()=>({responseTypeCode:"MCQ",selectedOptionId:option.id}))}/>{option.text}</label>)}</div>;return <div><label>Programming language<select disabled={disabled} value={language} onChange={event=>{const next=event.target.value;setLanguage(next);pending.current={language:next,source:code};if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),900);}}>{langs(question.programmingLanguages).map(value=><option key={value}>{value}</option>)}</select></label><CodingEditor languageCode={language} source={code} disabled={disabled} onChange={source=>{setCode(source);pending.current={language,source};if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),900);}}/></div>;}
