"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { browserApi, BffError } from "@/lib/api/browser-client";
import type { CandidateQuestion, SaveResponseInput, SavedResponse } from "@/lib/api/contracts";
import { formatRemaining, remainingSeconds } from "@/lib/attempt/timer";

type Status = "idle" | "saving" | "saved" | "conflict" | "error";
function languages(value: unknown): string[] { return Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : []; }

export function AttemptWorkspace({ attemptId }: { attemptId: string }) {
  const queryClient = useQueryClient(); const [active, setActive] = useState(0); const [local, setLocal] = useState<Record<number, SavedResponse>>({}); const [state, setState] = useState<Record<number, Status>>({}); const [inactive, setInactive] = useState(false); const [seconds, setSeconds] = useState<number | null>(null);
  const content = useQuery({ queryKey:["attempt-content", attemptId], queryFn: () => browserApi.content(attemptId) });
  const saved = useQuery({ queryKey:["attempt-responses", attemptId], queryFn: () => browserApi.responses(attemptId) });
  const queue = useRef<Record<number, Promise<void>>>({}); const versions = useRef<Record<number, number>>({}); const hydrated = useRef(false);
  useEffect(() => { if (!saved.data || hydrated.current) return; const mapped: Record<number, SavedResponse> = {}; for (const response of saved.data) { mapped[response.globalPosition] = response; versions.current[response.globalPosition] = response.version; } setLocal(mapped); hydrated.current = true; }, [saved.data]);
  const deadline = content.data?.deadlineAt ?? null;
  useEffect(() => { const tick = () => { const left = remainingSeconds(deadline); setSeconds(left); if (left === 0 && deadline) { setInactive(true); queryClient.invalidateQueries({ queryKey:["attempt-responses", attemptId] }); } }; tick(); const id = setInterval(tick, 1000); return () => clearInterval(id); }, [attemptId, deadline, queryClient]);
  const save = useCallback((position: number, make: (version: number) => Omit<SaveResponseInput, "expectedResponseVersion" | "clientMutationId">) => {
    const work = async () => { setState((s) => ({ ...s, [position]: "saving" })); const expected = versions.current[position] ?? 0; try { const response = await browserApi.saveResponse(attemptId, position, { ...make(expected), expectedResponseVersion: expected, clientMutationId: crypto.randomUUID() }, crypto.randomUUID()); versions.current[position] = response.version; setLocal((old) => ({ ...old, [position]: response })); setState((s) => ({ ...s, [position]: "saved" })); } catch (error) { if (error instanceof BffError && error.code === "RESPONSE_VERSION_CONFLICT") { const fresh = await queryClient.fetchQuery({ queryKey:["attempt-responses", attemptId], queryFn: () => browserApi.responses(attemptId), staleTime:0 }); const latest = fresh.find((r) => r.globalPosition === position); if (latest) { versions.current[position] = latest.version; setLocal((old) => ({ ...old, [position]: latest })); } setState((s) => ({ ...s, [position]: "conflict" })); } else if (error instanceof BffError && error.code === "INVALID_STATE") { setInactive(true); setState((s) => ({ ...s, [position]: "error" })); } else setState((s) => ({ ...s, [position]: "error" })); } };
    queue.current[position] = (queue.current[position] ?? Promise.resolve()).catch(() => undefined).then(work);
  }, [attemptId, queryClient]);
  const questions = content.data?.items ?? []; const current = questions[active]; const disabled = inactive || seconds === 0;
  if (content.isLoading || saved.isLoading) return <main className="attempt-main"><p>Loading assessment content…</p></main>;
  if (content.isError || saved.isError || !current) return <main className="attempt-main"><h1>Attempt unavailable</h1><p className="error">This attempt is inactive, expired, or could not be retrieved.</p></main>;
  return <div className="attempt"><aside className="attempt-nav"><strong>MockArena</strong><p className={seconds === 0 ? "error" : "muted"}>Time: {formatRemaining(seconds)}</p><div className="question-nav">{questions.map((q, i) => <button key={q.position} className={i === active ? "active" : ""} aria-label={`Question ${q.position}`} onClick={() => setActive(i)}>{q.position}</button>)}</div><p className="muted">{inactive ? "Attempt inactive" : "Autosave enabled"}</p></aside><main className="attempt-main"><p className="muted">Question {current.position} of {questions.length}</p><Question question={current} response={local[current.position]} disabled={disabled} state={state[current.position] ?? "idle"} onSave={save} /></main></div>;
}

function Question({ question, response, disabled, state, onSave }: { question: CandidateQuestion; response?: SavedResponse; disabled: boolean; state: Status; onSave: (position:number, make:(version:number)=>Omit<SaveResponseInput,"expectedResponseVersion"|"clientMutationId">)=>void }) {
  const [code, setCode] = useState(response?.sourceCode ?? ""); const [language, setLanguage] = useState(response?.programmingLanguage ?? languages(question.programmingLanguages)[0] ?? ""); const debounce = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => { setCode(response?.sourceCode ?? ""); setLanguage(response?.programmingLanguage ?? languages(question.programmingLanguages)[0] ?? ""); }, [question.position, question.programmingLanguages, response?.programmingLanguage, response?.sourceCode]);
  useEffect(() => () => { if (debounce.current) clearTimeout(debounce.current); }, []);
  const label = state === "saving" ? "Saving…" : state === "saved" ? "Saved" : state === "conflict" ? "A newer saved response was restored. Review before continuing." : state === "error" ? "Could not save. Your text remains in this page." : "";
  return <article className="panel"><h1>{question.title}</h1><p>{question.stem}</p>{question.questionTypeCode === "MCQ" ? <div>{question.options.map((option) => <label className="option" key={option.id}><input type="radio" name={`q-${question.position}`} disabled={disabled} checked={response?.selectedOptionId === option.id} onChange={() => onSave(question.position, () => ({ responseTypeCode:"MCQ", selectedOptionId:option.id }))} />{option.text}</label>)}</div> : <div><h2>Constraints</h2><p>{question.constraints}</p><h2>Examples</h2><pre>{JSON.stringify(question.examples, null, 2)}</pre><label>Programming language<select disabled={disabled} value={language} onChange={(e) => { const value=e.target.value; setLanguage(value); if (code.trim()) { if (debounce.current) clearTimeout(debounce.current); debounce.current=setTimeout(() => onSave(question.position, () => ({ responseTypeCode:"CODING", programmingLanguage:value, sourceCode:code })), 900); } }}>{languages(question.programmingLanguages).map((item) => <option key={item}>{item}</option>)}</select></label><label>Source code<textarea disabled={disabled} value={code} onChange={(e) => { const value=e.target.value; setCode(value); if (debounce.current) clearTimeout(debounce.current); debounce.current=setTimeout(() => onSave(question.position, () => ({ responseTypeCode:"CODING", programmingLanguage:language, sourceCode:value })), 900); }} /></label></div>}<p className={state === "conflict" || state === "error" ? "save-state error" : "save-state"} aria-live="polite">{label}</p></article>;
}
