package com.mockarena.question.config;
import com.fasterxml.jackson.databind.ObjectMapper; import com.mockarena.question.security.CodingEvaluationWorkloadTokenFilter; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.context.annotation.*; import org.springframework.http.*; import org.springframework.security.config.annotation.web.builders.HttpSecurity; import org.springframework.security.oauth2.core.*; import org.springframework.security.oauth2.jwt.*; import org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter; import org.springframework.security.web.SecurityFilterChain; import java.nio.file.*; import java.security.*; import java.security.interfaces.RSAPublicKey; import java.security.spec.*; import java.util.*;
@Configuration public class QuestionSecurityConfiguration {
 @Bean @ConditionalOnProperty(prefix="question.security",name="enabled",havingValue="true",matchIfMissing=true) RSAPublicKey questionJwtPublicKey(@Value("${question.security.jwt.public-key-path}") String path)throws Exception{if(path==null||path.isBlank())throw new IllegalStateException("MockArena JWT public key path is required");String p=Files.readString(Path.of(path)).replace("-----BEGIN PUBLIC KEY-----","").replace("-----END PUBLIC KEY-----","").replaceAll("\\s","");return (RSAPublicKey)KeyFactory.getInstance("RSA").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(p)));}
 @Bean @ConditionalOnProperty(prefix="question.security",name="enabled",havingValue="true",matchIfMissing=true) JwtDecoder jwtDecoder(RSAPublicKey key,@Value("${question.security.jwt.issuer}") String issuer,@Value("${question.security.jwt.audience}") String audience){NimbusJwtDecoder d=NimbusJwtDecoder.withPublicKey(key).build();OAuth2TokenValidator<Jwt> aud=j->j.getAudience().contains(audience)?OAuth2TokenValidatorResult.success():OAuth2TokenValidatorResult.failure(new OAuth2Error("invalid_token"));d.setJwtValidator(new DelegatingOAuth2TokenValidator<>(JwtValidators.createDefaultWithIssuer(issuer),aud));return d;}
 @Bean @ConditionalOnProperty(prefix="question.security",name="enabled",havingValue="true",matchIfMissing=true) SecurityFilterChain secured(HttpSecurity h,JwtDecoder d,ObjectMapper json,@Value("${question.workload-auth.coding-evaluation.token:}")String workloadToken)throws Exception{if(workloadToken==null||workloadToken.isBlank())throw new IllegalStateException("Question coding-evaluation workload token is required when security is enabled");return h.csrf(c->c.disable()).addFilterBefore(new CodingEvaluationWorkloadTokenFilter(workloadToken,json),BearerTokenAuthenticationFilter.class).authorizeHttpRequests(a->a.requestMatchers("/actuator/health/**","/internal/**").permitAll().anyRequest().authenticated()).oauth2ResourceServer(o->o.jwt(j->j.decoder(d)).authenticationEntryPoint((r,s,e)->error(s,json,HttpStatus.UNAUTHORIZED,"UNAUTHENTICATED"))).build();}
 @Bean @ConditionalOnProperty(prefix="question.security",name="enabled",havingValue="false") SecurityFilterChain unsecured(HttpSecurity h)throws Exception{return h.csrf(c->c.disable()).authorizeHttpRequests(a->a.anyRequest().permitAll()).build();}
 static void error(jakarta.servlet.http.HttpServletResponse s,ObjectMapper j,HttpStatus status,String code)throws java.io.IOException{s.setStatus(status.value());s.setContentType(MediaType.APPLICATION_JSON_VALUE);j.writeValue(s.getOutputStream(),Map.of("code",code,"message","Authentication is required"));}
}
