package com.mockarena.assessment.domain;
import jakarta.persistence.*; import java.time.*; import java.util.*;
@Entity @Table(name="coding_evaluation_outbox",schema="assessment") public class CodingEvaluationOutbox {
 @Id private UUID outboxId; @Column(nullable=false,updatable=false) private UUID attemptId; @Column(nullable=false,updatable=false) private int globalPosition; @Column(nullable=false,updatable=false) private UUID questionVersionId; @Column(updatable=false,length=64) private String sourceFingerprint; @Column(nullable=false,updatable=false) private String eventType; @Column(nullable=false) private String deliveryStatus; @Column(nullable=false) private int deliveryAttempts; private Instant nextAttemptAt; private String leaseOwner; private Instant leaseUntil,deliveredAt; @Version private long version; @Column(nullable=false,updatable=false) private Instant createdAt; @Column(nullable=false) private Instant updatedAt;
 protected CodingEvaluationOutbox(){} public CodingEvaluationOutbox(UUID id,SubmittedCodingResponseSnapshot snapshot,Instant now){outboxId=id;attemptId=snapshot.attemptId();globalPosition=snapshot.globalPosition();questionVersionId=snapshot.questionVersionId();sourceFingerprint=snapshot.sourceFingerprint();eventType="CODING_EVALUATION_REQUESTED";deliveryStatus="PENDING";deliveryAttempts=0;nextAttemptAt=now;createdAt=now;updatedAt=now;}
 public UUID outboxId(){return outboxId;} public UUID attemptId(){return attemptId;} public int globalPosition(){return globalPosition;} public UUID questionVersionId(){return questionVersionId;} public String sourceFingerprint(){return sourceFingerprint;} public String eventType(){return eventType;} public String deliveryStatus(){return deliveryStatus;} public int deliveryAttempts(){return deliveryAttempts;} public Instant nextAttemptAt(){return nextAttemptAt;} public Instant deliveredAt(){return deliveredAt;}
 public void claim(String owner,Instant until,Instant now){deliveryStatus="IN_FLIGHT";leaseOwner=owner;leaseUntil=until;deliveryAttempts++;updatedAt=now;}
 public void delivered(Instant now){deliveryStatus="DELIVERED";leaseOwner=null;leaseUntil=null;deliveredAt=now;updatedAt=now;}
 public void retry(Instant next,Instant now){deliveryStatus="PENDING";leaseOwner=null;leaseUntil=null;nextAttemptAt=next;updatedAt=now;}
}
